import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import StoreProvider from "./StoreProvider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Bube Boutique",
  description: "Generated by create next app",
};

// Opt out of caching for all data requests in the route segment
export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className="scroll-smooth"
        style={{ scrollBehavior: "smooth" }}
      >
        <body className="overflow-x-hidden font-custom scroll-smooth">
          <StoreProvider>
            <Header />
            {children}
            <Footer />
          </StoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
